### ISSUE TITLE
Feature request: Supply precompiled binaries for windows

### ISSUE THREAD

**Issue by advert665** [unpaper/unpaper#120]
Would it be possible to provide precompiled binaries for windows users? The meson build process does not play nicely with powershell and keeps giving a `Dependency "libavformat" not found, tried pkgconfig and cmake` error, despite me having ffmpeg installed via winget and on the path. I'd really rather not have to install WSL for this one application... Thanks!

**Comment by Flameeyes** [comment]
There's some discussion of this in #52 but for the moment I'm not planning on providing prebuilt binaries (I haven't even tested build on Windows), and unpaper is in fairly deep maintenance mode.

Note that the copy of FFmpeg installed with winget is likely missing the development files necessary to build against it, which is why you're receiving those errors.

**Comment by StephS** [comment]
FYI I tried the MSYS method in the https://github.com/unpaper/unpaper/issues/52 however I had trouble getting libav to compile. Something with the current GNU Make tools causing an error. I found this patch and applied it https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=effadce6c756247ea8bae32dc13bb3e6f464f0eb
Copied below for records
`diff --git a/libavcodec/x86/mathops.h b/libavcodec/x86/mathops.h
index 6298f5ed19..ca7e2dffc1 100644
--- a/libavcodec/x86/mathops.h
+++ b/libavcodec/x86/mathops.h
@@ -35,12 +35,20 @@
 static av_always_inline av_const int MULL(int a, int b, unsigned shift)
 {
     int rt, dummy;
+    if (__builtin_constant_p(shift))
     __asm__ (
         "imull %3               \n\t"
         "shrdl %4, %%edx, %%eax \n\t"
         :"=a"(rt), "=d"(dummy)
-        :"a"(a), "rm"(b), "ci"((uint8_t)shift)
+        :"a"(a), "rm"(b), "i"(shift & 0x1F)
     );
+    else
+        __asm__ (
+            "imull %3               \n\t"
+            "shrdl %4, %%edx, %%eax \n\t"
+            :"=a"(rt), "=d"(dummy)
+            :"a"(a), "rm"(b), "c"((uint8_t)shift)
+        );
     return rt;
 }
 
@@ -113,19 +121,31 @@ __asm__ volatile(\
 // avoid +32 for shift optimization (gcc should do that ...)
 #define NEG_SSR32 NEG_SSR32
 static inline  int32_t NEG_SSR32( int32_t a, int8_t s){
+    if (__builtin_constant_p(s))
     __asm__ ("sarl %1, %0\n\t"
          : "+r" (a)
-         : "ic" ((uint8_t)(-s))
+         : "i" (-s & 0x1F)
     );
+    else
+        __asm__ ("sarl %1, %0\n\t"
+               : "+r" (a)
+               : "c" ((uint8_t)(-s))
+        );
     return a;
 }
 
 #define NEG_USR32 NEG_USR32
 static inline uint32_t NEG_USR32(uint32_t a, int8_t s){
+    if (__builtin_constant_p(s))
     __asm__ ("shrl %1, %0\n\t"
          : "+r" (a)
-         : "ic" ((uint8_t)(-s))
+         : "i" (-s & 0x1F)
     );
+    else
+        __asm__ ("shrl %1, %0\n\t"
+               : "+r" (a)
+               : "c" ((uint8_t)(-s))
+        );
     return a;
 }
 
-- 
2.30.2
`
I downloaded libav from https://github.com/libav/libav/releases/tag/v11.11
the autoreconf didn't work, I tried pacman -S autoconf-wrapper but it still didn't work because it was missing configure.ac due to the switch to meson here https://github.com/unpaper/unpaper/commit/d999d0725aa639e3ab32164362be8a07996b54a0

What this actually means is that the only version you can install using the method in that issue, is by using this PR version
https://github.com/unpaper/unpaper/commit/7d1f5a70b4563ef5d23e7a9b45097ba9244c26e4

If you want to compile the latest version, you can still use msys, however you will need to do a few things. first install all the python3 stuff
`pacman -S \
    mingw-w64-x86_64-gcc \
    mingw-w64-x86_64-python3 \
    mingw-w64-x86_64-python3-pip \
    mingw-w64-x86_64-python3-setuptools`
then install meson pytest ninja
and then dependencies for pillow using the install guide https://pillow.readthedocs.io/en/latest/installation.html#external-libraries 
`pacman -S \
    mingw-w64-x86_64-libjpeg-turbo \
    mingw-w64-x86_64-zlib \
    mingw-w64-x86_64-libtiff \
    mingw-w64-x86_64-freetype \
    mingw-w64-x86_64-lcms2 \
    mingw-w64-x86_64-libwebp \
    mingw-w64-x86_64-openjpeg2 \
    mingw-w64-x86_64-libimagequant \
    mingw-w64-x86_64-libraqm

export SETUPTOOLS_USE_DISTUTILS=stdlib
python3 -m pip install --upgrade Pillow --no-binary :all:`

install libav (not sure about this, but it works)
`pacman -S mingw-w64-x86_64-gst-libav`

then download and configure unpaper
`git clone https://github.com/unpaper/unpaper.git ./unpaper
cd unpaper
 meson setup builddir`

I had to download ffmpeg for windows and copy all the DLL files into the executable folder. But so far it seems to work.
