### ISSUE TITLE
Build on fedora 32

### ISSUE THREAD

**Issue by long-walk** [unpaper/unpaper#74]
For Fedora 32 I had to run this commands to build it.

```
git clone https://github.com/unpaper/unpaper.git
cd unpaper/
aclocal
automake --add-missing
autoconf
./configure
make
sudo make install
// I had to open the terminal again that binary was found 
unpaper --version
```

**Comment by Flameeyes** [comment]
That is normal Autotools installation. Worth noting:

 * you can use `autoreconf -fis` instead of the three separate calls, it's faster;
 * you can use `hash -r` to avoid reopening the terminal to autocomplete the binary; calling `unpaper` explicitly should work even if tab completion doesn't find it.

**Comment by long-walk** [comment]
Oh thanks for that hint. I will test it.

**Comment by Hnasar** [comment]
`autoreconf -fis` would be nice to add to the README. It wasn't obvious to me either :sweat: 
Thanks for maintianing this!
