### ISSUE TITLE
Clarify which licenses apply to what code

### ISSUE THREAD

**Issue by p** [unpaper/unpaper#99]
The readme for unpaper says:

> Originally written by Jens Gulden — see AUTHORS for more information. Licensed under GNU GPL v2 — see COPYING for more information.

The `COPYING` file referenced is missing.

The `AUTHORS` file which is also referenced contains this line:

```
# SPDX-License-Identifier: GPL-2.0-only
```

This implies that the entire codebase is probably covered by GPL 2.0 only, but then appears to contradict the 3 licenses in `LICENSES` subdirectory (https://github.com/unpaper/unpaper/tree/main/LICENSES).

The 3 license files listed in the `LICENSES` subdirectory do not specify which license applies to what code.

It would be helpful for both contributors and distributors to clarify what code is covered under which license in `LICENSES`, as well as have an unambiguous statement as to which license covers the entire project.

**Comment by Flameeyes** [comment]
I guess I should replace the reference to `COPYING` in the README after all.

As for clarifying, unpaper follows the [REUSE](https://reuse.software/) specifications, so each source file provides SPDX identifiers stating which license applies to it. This is unambiguous.

Because of the nature of GNU GPLv2, and the fact that the other licenses only apply to build script and other support should treat the combined project (in source and binary form) as GNU GPLv2.

**Comment by p** [comment]
> As for clarifying, unpaper follows the REUSE specifications, so each source file provides SPDX identifiers stating which license applies to it. This is unambiguous.



This would be helpful to include somewhere in the readme file. It looks to be a good system but personally this is the first project I've come across that utilizes it.

**Comment by Flameeyes** [comment]
It's the same system as used by KDE: https://community.kde.org/Guidelines_and_HOWTOs/Licensing

I'm happy to merge a pull request to clarify this if you think it's needed…

**Comment by p** [comment]
I submitted https://github.com/unpaper/unpaper/pull/100, let me know if this is along the lines of what you were thinking.
